### ISSUE TITLE
Red elder influenced maps hidden

### ISSUE THREAD

**Issue by ThePsyjo** [ffhighwind/PoE-Price-Lister#1]
https://github.com/ffhighwind/PoE-Price-Lister/blob/3c859823ec03368748d77587590f416d332cab93/Resources/Filters/L4_Very_Strict_Highwind.filter#L2398-L2404

Red elder maps are not shown.
I guess it should be sufficient to move maps somewhere above the block i referenced. The other way would be setting item class explicitly there.

Maybe a `Continue` can do the trick in this block too. It shows the map but I haven't tested it for other items.

**Comment by ffhighwind** [comment]
I will make an update some time this weekend. I suspect sockets > 0 should
fix the issue.

**Comment by ffhighwind** [comment]
I ended up reworking most of the filter... and it's still not finished.
Probably 15 hours of work so far. Still need to test it when it's done too.
Hopefully I can finish it in the next couple of days.

**Comment by ffhighwind** [comment]
The update is finished, but it needs more testing before I move it to my profile. The solution to this was to move Maps to the top of the filter.
